### PR TITLE
Fixed getMaxTextTemplate with column formatter

### PR DESCRIPTION
**Pull request by GreggGut**
In getMaxTextTemplate, pass the actual object to the column formatter and not the whole array of objects

### CODE REVIEW

**Comment by naresh-n** [comment]
Sometimes formatter needs other fields to format the data.For E.g two or more fields are required to determine the format. That was the reason we pass whole object.

**Comment by GreggGut** [comment]
In the current version you're not passing the actual object but the whole array of objects. My proposed fix passes the particular (whole) object instead of the array. 
This is because the formatter expects 1 object and not the whole array.

**Comment by naresh-n** [comment]
Merged,

Thank you. Sorry for the delay.I was in vacation.

**Comment by GreggGut** [comment]
Thanks for the merge and the great plugin!

**Pull request merged**
